global using System.Collections.Concurrent;
global using System.Collections.Immutable;
global using System.ComponentModel;
global using System.Configuration;
global using System.Diagnostics;
global using System.Globalization;
global using System.Reflection;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using FluentValidation;
global using JetBrains.Annotations;
global using CryptoCoinsParser.Application.HostedServices;
global using CryptoCoinsParser.Application.Resources.Localization;
global using CryptoCoinsParser.Application.TelegramBot;
global using CryptoCoinsParser.Application.TelegramBot.BotMarkup;
global using CryptoCoinsParser.Application.TelegramBot.CommandHandlers;
global using CryptoCoinsParser.Application.TelegramBot.CommandHandlers.DeveloperCommands;
global using CryptoCoinsParser.Application.TelegramBot.CommandHandlers.Settings;
global using CryptoCoinsParser.Application.TelegramBot.Configuration;
global using CryptoCoinsParser.Application.TelegramBot.Extensions;
global using CryptoCoinsParser.Application.TelegramBot.Models;
global using CryptoCoinsParser.Application.TelegramBot.Services.Decorators;
global using CryptoCoinsParser.Application.TelegramBot.Services.Implementation;
global using CryptoCoinsParser.Application.TelegramBot.Services.Interfaces;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Configuration;
global using Newtonsoft.Json;
global using Scriban;
global using Shared;
global using Shared.Delegates;
global using Shared.Models;
global using Telegram.Bot;
global using Telegram.Bot.Args;
global using Telegram.Bot.Exceptions;
global using Telegram.Bot.Requests;
global using Telegram.Bot.Types;
global using Telegram.Bot.Types.Enums;
global using Telegram.Bot.Types.ReplyMarkups;
global using static System.String;
global using static CryptoCoinsParser.Application.Resources.Localization.Localization;
global using static CryptoCoinsParser.Application.TelegramBot.BotMarkup.Markup;
global using static CryptoCoinsParser.Application.TelegramBot.Configuration.BotCommand;
global using static CryptoCoinsParser.Application.TelegramBot.Separator;
global using static Telegram.Bot.Types.ReplyMarkups.InlineKeyboardButton;
global using BotCommand_ = CryptoCoinsParser.Application.TelegramBot.Configuration.BotCommand;
global using CryptoCoinsParser.Domain.DbEntities;
global using System.Net;
global using CryptoCoinsParser.Binance.Scraper.Services;
global using CryptoCoinsParser.Bybit.Scraper.Services;
global using CryptoCoinsParser.Domain.Enums;
global using CryptoCoinsParser.KuCoin.Scraper.Services;
global using CryptoCoinsParser.Okx.Scraper.Services;
global using CryptoCoinsParser.Persistence.Repositories.Implementation;
global using CryptoCoinsParser.Persistence.Repositories.Interfaces;
global using Polly;
global using Polly.Extensions.Http;
global using Polly.Timeout;
global using CryptoCoinsParser.Scrapers.Interfaces;
global using CryptoCoinsParser.Scrapers.Models;
global using CryptoCoinsParser.Scrapers.Utils;
global using OxyPlot;
global using OxyPlot.SkiaSharp;
global using SkiaSharp;
