version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - lingopractices
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: reallyStrongPwd#123

networks:
  lingopractices:
    name: lingopractices