//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCoinsParser.Application.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CryptoCoinsParser.Application.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WantPracticeLanguage {
            get {
                return ResourceManager.GetString("WantPracticeLanguage", resourceCulture);
            }
        }
        
        internal static string ButtonTextIAmReady {
            get {
                return ResourceManager.GetString("ButtonTextIAmReady", resourceCulture);
            }
        }
        
        internal static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        internal static string ButtonTextYes {
            get {
                return ResourceManager.GetString("ButtonTextYes", resourceCulture);
            }
        }
        
        internal static string ButtonTextNo {
            get {
                return ResourceManager.GetString("ButtonTextNo", resourceCulture);
            }
        }
        
        internal static string LanguageIsNotRecognized {
            get {
                return ResourceManager.GetString("LanguageIsNotRecognized", resourceCulture);
            }
        }
        
        internal static string SelectMeetingLanguageYouWouldLikeToPractice {
            get {
                return ResourceManager.GetString("SelectMeetingLanguageYouWouldLikeToPractice", resourceCulture);
            }
        }
        
        internal static string LanguageSet {
            get {
                return ResourceManager.GetString("LanguageSet", resourceCulture);
            }
        }
        
        internal static string PracticeEnglishAsking {
            get {
                return ResourceManager.GetString("PracticeEnglishAsking", resourceCulture);
            }
        }
        
        internal static string CMLanguageLevelAsk {
            get {
                return ResourceManager.GetString("CMLanguageLevelAsk", resourceCulture);
            }
        }
        
        internal static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        internal static string ShowAllMeetings {
            get {
                return ResourceManager.GetString("ShowAllMeetings", resourceCulture);
            }
        }
        
        internal static string SelectTopic {
            get {
                return ResourceManager.GetString("SelectTopic", resourceCulture);
            }
        }
        
        internal static string ButtonTextRandomTopic {
            get {
                return ResourceManager.GetString("ButtonTextRandomTopic", resourceCulture);
            }
        }
        
        internal static string ViewTopicQuestions {
            get {
                return ResourceManager.GetString("ViewTopicQuestions", resourceCulture);
            }
        }
        
        internal static string SelectMeetingTime {
            get {
                return ResourceManager.GetString("SelectMeetingTime", resourceCulture);
            }
        }
        
        internal static string SelectMeetingLanguageLevel {
            get {
                return ResourceManager.GetString("SelectMeetingLanguageLevel", resourceCulture);
            }
        }
        
        internal static string HowManyPeople {
            get {
                return ResourceManager.GetString("HowManyPeople", resourceCulture);
            }
        }
        
        internal static string DbUpdateException {
            get {
                return ResourceManager.GetString("DbUpdateException", resourceCulture);
            }
        }
        
        internal static string MeetingCreated {
            get {
                return ResourceManager.GetString("MeetingCreated", resourceCulture);
            }
        }
        
        internal static string ButtonTextPickAnotherDate {
            get {
                return ResourceManager.GetString("ButtonTextPickAnotherDate", resourceCulture);
            }
        }
        
        internal static string ButtonTextPickAnotherTime {
            get {
                return ResourceManager.GetString("ButtonTextPickAnotherTime", resourceCulture);
            }
        }
        
        internal static string ButtonTextConfirm {
            get {
                return ResourceManager.GetString("ButtonTextConfirm", resourceCulture);
            }
        }
        
        internal static string SelectMeetingDate {
            get {
                return ResourceManager.GetString("SelectMeetingDate", resourceCulture);
            }
        }
        
        internal static string SelectOneOfLanguages {
            get {
                return ResourceManager.GetString("SelectOneOfLanguages", resourceCulture);
            }
        }
        
        internal static string JMSelectLanguageLevel {
            get {
                return ResourceManager.GetString("JMSelectLanguageLevel", resourceCulture);
            }
        }
        
        internal static string AlreadyJoined {
            get {
                return ResourceManager.GetString("AlreadyJoined", resourceCulture);
            }
        }
        
        internal static string ButtonTextPickAnotherLanguage {
            get {
                return ResourceManager.GetString("ButtonTextPickAnotherLanguage", resourceCulture);
            }
        }
        
        internal static string ButtonTextPickAnotherLanguageLevel {
            get {
                return ResourceManager.GetString("ButtonTextPickAnotherLanguageLevel", resourceCulture);
            }
        }
        
        internal static string NoMatchingMeetings {
            get {
                return ResourceManager.GetString("NoMatchingMeetings", resourceCulture);
            }
        }
        
        internal static string SelectMeetingLanguage {
            get {
                return ResourceManager.GetString("SelectMeetingLanguage", resourceCulture);
            }
        }
        
        internal static string MeetingNotFound {
            get {
                return ResourceManager.GetString("MeetingNotFound", resourceCulture);
            }
        }
        
        internal static string MeetingAlreadyCanceled {
            get {
                return ResourceManager.GetString("MeetingAlreadyCanceled", resourceCulture);
            }
        }
        
        internal static string MeetingCanceled {
            get {
                return ResourceManager.GetString("MeetingCanceled", resourceCulture);
            }
        }
        
        internal static string CantLeaveMeeting {
            get {
                return ResourceManager.GetString("CantLeaveMeeting", resourceCulture);
            }
        }
        
        internal static string OperationDeclined {
            get {
                return ResourceManager.GetString("OperationDeclined", resourceCulture);
            }
        }
        
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        internal static string InitialMessage {
            get {
                return ResourceManager.GetString("InitialMessage", resourceCulture);
            }
        }
        
        internal static string LanguageLevelSet {
            get {
                return ResourceManager.GetString("LanguageLevelSet", resourceCulture);
            }
        }
        
        internal static string TitleTextSelectLanguageLevel {
            get {
                return ResourceManager.GetString("TitleTextSelectLanguageLevel", resourceCulture);
            }
        }
        
        internal static string ButtonTextShowAllLevels {
            get {
                return ResourceManager.GetString("ButtonTextShowAllLevels", resourceCulture);
            }
        }
        
        internal static string UserLeftMeetingTemplate {
            get {
                return ResourceManager.GetString("UserLeftMeetingTemplate", resourceCulture);
            }
        }
        
        internal static string CreateMeetingTemplate {
            get {
                return ResourceManager.GetString("CreateMeetingTemplate", resourceCulture);
            }
        }
        
        internal static string QuestionsTemplate {
            get {
                return ResourceManager.GetString("QuestionsTemplate", resourceCulture);
            }
        }
        
        internal static string YouJoinedMeeting {
            get {
                return ResourceManager.GetString("YouJoinedMeeting", resourceCulture);
            }
        }
        
        internal static string UserJoinedMeeting {
            get {
                return ResourceManager.GetString("UserJoinedMeeting", resourceCulture);
            }
        }
        
        internal static string LocationSet {
            get {
                return ResourceManager.GetString("LocationSet", resourceCulture);
            }
        }
        
        internal static string UnableResolveLocation {
            get {
                return ResourceManager.GetString("UnableResolveLocation", resourceCulture);
            }
        }
        
        internal static string CouldNotResolveLocation {
            get {
                return ResourceManager.GetString("CouldNotResolveLocation", resourceCulture);
            }
        }
        
        internal static string CreateMeetingAskLocation {
            get {
                return ResourceManager.GetString("CreateMeetingAskLocation", resourceCulture);
            }
        }
        
        internal static string HelpFindPartner {
            get {
                return ResourceManager.GetString("HelpFindPartner", resourceCulture);
            }
        }
        
        internal static string WhatWouldYouLikeToChange {
            get {
                return ResourceManager.GetString("WhatWouldYouLikeToChange", resourceCulture);
            }
        }
        
        internal static string DescriptionCreateMeeting {
            get {
                return ResourceManager.GetString("DescriptionCreateMeeting", resourceCulture);
            }
        }
        
        internal static string DescriptionRandomTopic {
            get {
                return ResourceManager.GetString("DescriptionRandomTopic", resourceCulture);
            }
        }
        
        internal static string DescriptionJoinMeeting {
            get {
                return ResourceManager.GetString("DescriptionJoinMeeting", resourceCulture);
            }
        }
        
        internal static string DescriptionMyMeetings {
            get {
                return ResourceManager.GetString("DescriptionMyMeetings", resourceCulture);
            }
        }
        
        internal static string DescriptionSettings {
            get {
                return ResourceManager.GetString("DescriptionSettings", resourceCulture);
            }
        }
        
        internal static string DescriptionSetMeetingLanguage {
            get {
                return ResourceManager.GetString("DescriptionSetMeetingLanguage", resourceCulture);
            }
        }
        
        internal static string DescriptionSetMeetingLanguageLevel {
            get {
                return ResourceManager.GetString("DescriptionSetMeetingLanguageLevel", resourceCulture);
            }
        }
        
        internal static string DescriptionSetYourLocation {
            get {
                return ResourceManager.GetString("DescriptionSetYourLocation", resourceCulture);
            }
        }
        
        internal static string DescriptionContactUs {
            get {
                return ResourceManager.GetString("DescriptionContactUs", resourceCulture);
            }
        }
        
        internal static string DescriptionSetGender {
            get {
                return ResourceManager.GetString("DescriptionSetGender", resourceCulture);
            }
        }
        
        internal static string ButtonTextFemale {
            get {
                return ResourceManager.GetString("ButtonTextFemale", resourceCulture);
            }
        }
        
        internal static string ButtonTextMale {
            get {
                return ResourceManager.GetString("ButtonTextMale", resourceCulture);
            }
        }
        
        internal static string ButtonTextSkipGender {
            get {
                return ResourceManager.GetString("ButtonTextSkipGender", resourceCulture);
            }
        }
        
        internal static string GenderText {
            get {
                return ResourceManager.GetString("GenderText", resourceCulture);
            }
        }
        
        internal static string GenderSet {
            get {
                return ResourceManager.GetString("GenderSet", resourceCulture);
            }
        }
        
        internal static string ButtonTextLeaveMeeting {
            get {
                return ResourceManager.GetString("ButtonTextLeaveMeeting", resourceCulture);
            }
        }
        
        internal static string ViewMeetingTemplate {
            get {
                return ResourceManager.GetString("ViewMeetingTemplate", resourceCulture);
            }
        }
        
        internal static string ButtonTextJoin {
            get {
                return ResourceManager.GetString("ButtonTextJoin", resourceCulture);
            }
        }
        
        internal static string GenderNotSet {
            get {
                return ResourceManager.GetString("GenderNotSet", resourceCulture);
            }
        }
        
        internal static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        internal static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        internal static string AuthorizeWithGoogle {
            get {
                return ResourceManager.GetString("AuthorizeWithGoogle", resourceCulture);
            }
        }
        
        internal static string AuthorizeWithGoogleSuccess {
            get {
                return ResourceManager.GetString("AuthorizeWithGoogleSuccess", resourceCulture);
            }
        }
        
        internal static string GoogleMeetTitle {
            get {
                return ResourceManager.GetString("GoogleMeetTitle", resourceCulture);
            }
        }
        
        internal static string AlreadyAuthorizedWithGoogle {
            get {
                return ResourceManager.GetString("AlreadyAuthorizedWithGoogle", resourceCulture);
            }
        }
        
        internal static string StartBotCommand {
            get {
                return ResourceManager.GetString("StartBotCommand", resourceCulture);
            }
        }
        
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string ButtonTextNext {
            get {
                return ResourceManager.GetString("ButtonTextNext", resourceCulture);
            }
        }
        
        internal static string ForgotToProvideCalendarPermissions {
            get {
                return ResourceManager.GetString("ForgotToProvideCalendarPermissions", resourceCulture);
            }
        }
        
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        internal static string DescriptionSetInterfaceLanguage {
            get {
                return ResourceManager.GetString("DescriptionSetInterfaceLanguage", resourceCulture);
            }
        }
        
        internal static string InterfaceLanguageSet {
            get {
                return ResourceManager.GetString("InterfaceLanguageSet", resourceCulture);
            }
        }
        
        internal static string AvailableUILanguages {
            get {
                return ResourceManager.GetString("AvailableUILanguages", resourceCulture);
            }
        }
        
        internal static string JoinGoogleMeetMeeting {
            get {
                return ResourceManager.GetString("JoinGoogleMeetMeeting", resourceCulture);
            }
        }
        
        internal static string ButtonTextViewTopicQuestions {
            get {
                return ResourceManager.GetString("ButtonTextViewTopicQuestions", resourceCulture);
            }
        }
        
        internal static string NotPendingMeetings {
            get {
                return ResourceManager.GetString("NotPendingMeetings", resourceCulture);
            }
        }
        
        internal static string SettingGenderTitle {
            get {
                return ResourceManager.GetString("SettingGenderTitle", resourceCulture);
            }
        }
        
        internal static string ButtonTextCreateNewMeeting {
            get {
                return ResourceManager.GetString("ButtonTextCreateNewMeeting", resourceCulture);
            }
        }
        
        internal static string CantJoinMeetingSameTime {
            get {
                return ResourceManager.GetString("CantJoinMeetingSameTime", resourceCulture);
            }
        }
        
        internal static string SelectAnotherMeeting {
            get {
                return ResourceManager.GetString("SelectAnotherMeeting", resourceCulture);
            }
        }
        
        internal static string DescriptionCreateTopic {
            get {
                return ResourceManager.GetString("DescriptionCreateTopic", resourceCulture);
            }
        }
        
        internal static string TitleTextTopicNameOnModerating {
            get {
                return ResourceManager.GetString("TitleTextTopicNameOnModerating", resourceCulture);
            }
        }
        
        internal static string TitleTextUserTriedAddTopic {
            get {
                return ResourceManager.GetString("TitleTextUserTriedAddTopic", resourceCulture);
            }
        }
        
        internal static string TitleTextWriteTopicName {
            get {
                return ResourceManager.GetString("TitleTextWriteTopicName", resourceCulture);
            }
        }
        
        internal static string TitleTextTopicAlreadyExist {
            get {
                return ResourceManager.GetString("TitleTextTopicAlreadyExist", resourceCulture);
            }
        }
        
        internal static string TitleTextTopicCreated {
            get {
                return ResourceManager.GetString("TitleTextTopicCreated", resourceCulture);
            }
        }
        
        internal static string TopicQuestionAdded {
            get {
                return ResourceManager.GetString("TopicQuestionAdded", resourceCulture);
            }
        }
        
        internal static string TitleTextWriteTopicQuestion {
            get {
                return ResourceManager.GetString("TitleTextWriteTopicQuestion", resourceCulture);
            }
        }
        
        internal static string TitleTextThankYou {
            get {
                return ResourceManager.GetString("TitleTextThankYou", resourceCulture);
            }
        }
        
        internal static string ButtonTextAddQuestion {
            get {
                return ResourceManager.GetString("ButtonTextAddQuestion", resourceCulture);
            }
        }
        
        internal static string ButtonTextAddOneMore {
            get {
                return ResourceManager.GetString("ButtonTextAddOneMore", resourceCulture);
            }
        }
        
        internal static string ButtonTextComplete {
            get {
                return ResourceManager.GetString("ButtonTextComplete", resourceCulture);
            }
        }
        
        internal static string ButtonTextTryAgainTopicName {
            get {
                return ResourceManager.GetString("ButtonTextTryAgainTopicName", resourceCulture);
            }
        }
        
        internal static string TitleTextCantApproveQuestion {
            get {
                return ResourceManager.GetString("TitleTextCantApproveQuestion", resourceCulture);
            }
        }
        
        internal static string TitleTextQuestionIsOnModerating {
            get {
                return ResourceManager.GetString("TitleTextQuestionIsOnModerating", resourceCulture);
            }
        }
        
        internal static string TitleTextUserWantsAddQuestion {
            get {
                return ResourceManager.GetString("TitleTextUserWantsAddQuestion", resourceCulture);
            }
        }
        
        internal static string CreatorCancelledMeeting {
            get {
                return ResourceManager.GetString("CreatorCancelledMeeting", resourceCulture);
            }
        }
        
        internal static string TitleTextCantApproveTopic {
            get {
                return ResourceManager.GetString("TitleTextCantApproveTopic", resourceCulture);
            }
        }
        
        internal static string SignUpSuccess {
            get {
                return ResourceManager.GetString("SignUpSuccess", resourceCulture);
            }
        }
        
        internal static string TitleTextTopicNotSelected {
            get {
                return ResourceManager.GetString("TitleTextTopicNotSelected", resourceCulture);
            }
        }
        
        internal static string ButtonTextWithoutTopic {
            get {
                return ResourceManager.GetString("ButtonTextWithoutTopic", resourceCulture);
            }
        }
        
        internal static string ButtonTextTryAgainTopicQuestion {
            get {
                return ResourceManager.GetString("ButtonTextTryAgainTopicQuestion", resourceCulture);
            }
        }
        
        internal static string ButtonTextSetNotificationPreferences {
            get {
                return ResourceManager.GetString("ButtonTextSetNotificationPreferences", resourceCulture);
            }
        }
        
        internal static string TitleTextNotificationCreated {
            get {
                return ResourceManager.GetString("TitleTextNotificationCreated", resourceCulture);
            }
        }
        
        internal static string TitleTextNotificationAlreadyExist {
            get {
                return ResourceManager.GetString("TitleTextNotificationAlreadyExist", resourceCulture);
            }
        }
        
        internal static string TitleTextNotificationPreferences {
            get {
                return ResourceManager.GetString("TitleTextNotificationPreferences", resourceCulture);
            }
        }
        
        internal static string SelectLanguageNotificationPreferences {
            get {
                return ResourceManager.GetString("SelectLanguageNotificationPreferences", resourceCulture);
            }
        }
        
        internal static string ButtonTextNextMeeting {
            get {
                return ResourceManager.GetString("ButtonTextNextMeeting", resourceCulture);
            }
        }
        
        internal static string ButtonTextPreviousMeeting {
            get {
                return ResourceManager.GetString("ButtonTextPreviousMeeting", resourceCulture);
            }
        }
        
        internal static string ButtonTextNextTopics {
            get {
                return ResourceManager.GetString("ButtonTextNextTopics", resourceCulture);
            }
        }
        
        internal static string ButtonTextPreviousTopics {
            get {
                return ResourceManager.GetString("ButtonTextPreviousTopics", resourceCulture);
            }
        }
        
        internal static string ButtonTextPreviousMonth {
            get {
                return ResourceManager.GetString("ButtonTextPreviousMonth", resourceCulture);
            }
        }
        
        internal static string ButtonTextNextMonth {
            get {
                return ResourceManager.GetString("ButtonTextNextMonth", resourceCulture);
            }
        }
        
        internal static string NoFreePlacesWhenJoin {
            get {
                return ResourceManager.GetString("NoFreePlacesWhenJoin", resourceCulture);
            }
        }
        
        internal static string TitleTextPreferncesEdited {
            get {
                return ResourceManager.GetString("TitleTextPreferncesEdited", resourceCulture);
            }
        }
        
        internal static string ButtonTextToSettingMenu {
            get {
                return ResourceManager.GetString("ButtonTextToSettingMenu", resourceCulture);
            }
        }
        
        internal static string DescriptionTextSetGender {
            get {
                return ResourceManager.GetString("DescriptionTextSetGender", resourceCulture);
            }
        }
        
        internal static string ButtonTextSetUp {
            get {
                return ResourceManager.GetString("ButtonTextSetUp", resourceCulture);
            }
        }
        
        internal static string ButtonTextGoToMenu {
            get {
                return ResourceManager.GetString("ButtonTextGoToMenu", resourceCulture);
            }
        }
        
        internal static string ButtonTextChangeNotification {
            get {
                return ResourceManager.GetString("ButtonTextChangeNotification", resourceCulture);
            }
        }
        
        internal static string CantJoinMeetingIsInProgressOrEnded {
            get {
                return ResourceManager.GetString("CantJoinMeetingIsInProgressOrEnded", resourceCulture);
            }
        }
        
        internal static string ButtonTextIWillJoinNextTime {
            get {
                return ResourceManager.GetString("ButtonTextIWillJoinNextTime", resourceCulture);
            }
        }
        
        internal static string MessageTextSetLocation {
            get {
                return ResourceManager.GetString("MessageTextSetLocation", resourceCulture);
            }
        }
        
        internal static string NotificationsDisabled {
            get {
                return ResourceManager.GetString("NotificationsDisabled", resourceCulture);
            }
        }
        
        internal static string NotificationsEnabled {
            get {
                return ResourceManager.GetString("NotificationsEnabled", resourceCulture);
            }
        }
        
        internal static string CouldNotCreateGoogleMeetMeeting {
            get {
                return ResourceManager.GetString("CouldNotCreateGoogleMeetMeeting", resourceCulture);
            }
        }
        
        internal static string ButtonTextTurnOffNotifications {
            get {
                return ResourceManager.GetString("ButtonTextTurnOffNotifications", resourceCulture);
            }
        }
        
        internal static string TitleTextTurnOffNotificationFor {
            get {
                return ResourceManager.GetString("TitleTextTurnOffNotificationFor", resourceCulture);
            }
        }
        
        internal static string ButtonTextOneDay {
            get {
                return ResourceManager.GetString("ButtonTextOneDay", resourceCulture);
            }
        }
        
        internal static string ButtonTextOneWeek {
            get {
                return ResourceManager.GetString("ButtonTextOneWeek", resourceCulture);
            }
        }
        
        internal static string ButtonTextOneMonth {
            get {
                return ResourceManager.GetString("ButtonTextOneMonth", resourceCulture);
            }
        }
        
        internal static string TitleTextMeetingNotificationTurnedOff {
            get {
                return ResourceManager.GetString("TitleTextMeetingNotificationTurnedOff", resourceCulture);
            }
        }
        
        internal static string TitleTextTurnOnNotificationQuestion {
            get {
                return ResourceManager.GetString("TitleTextTurnOnNotificationQuestion", resourceCulture);
            }
        }
        
        internal static string ButtonTextYesTurnOn {
            get {
                return ResourceManager.GetString("ButtonTextYesTurnOn", resourceCulture);
            }
        }
        
        internal static string JoinMeetingCanceled {
            get {
                return ResourceManager.GetString("JoinMeetingCanceled", resourceCulture);
            }
        }
        
        internal static string MeetingAlreadyBegun {
            get {
                return ResourceManager.GetString("MeetingAlreadyBegun", resourceCulture);
            }
        }
        
        internal static string RequestLimitMessage {
            get {
                return ResourceManager.GetString("RequestLimitMessage", resourceCulture);
            }
        }
        
        internal static string ButtonTextGoBack {
            get {
                return ResourceManager.GetString("ButtonTextGoBack", resourceCulture);
            }
        }
        
        internal static string TitleTextNotificationByPreference {
            get {
                return ResourceManager.GetString("TitleTextNotificationByPreference", resourceCulture);
            }
        }
        
        internal static string TitleTextMeetingReminder {
            get {
                return ResourceManager.GetString("TitleTextMeetingReminder", resourceCulture);
            }
        }
        
        internal static string TitleTextNobodyJoinsMeeting {
            get {
                return ResourceManager.GetString("TitleTextNobodyJoinsMeeting", resourceCulture);
            }
        }
        
        internal static string MeetingMessage {
            get {
                return ResourceManager.GetString("MeetingMessage", resourceCulture);
            }
        }
        
        internal static string ButtonTextOpenWebApp {
            get {
                return ResourceManager.GetString("ButtonTextOpenWebApp", resourceCulture);
            }
        }
        
        internal static string ButtonTextUpTo5Min {
            get {
                return ResourceManager.GetString("ButtonTextUpTo5Min", resourceCulture);
            }
        }
        
        internal static string ButtonTextUpTo10Min {
            get {
                return ResourceManager.GetString("ButtonTextUpTo10Min", resourceCulture);
            }
        }
        
        internal static string ButtonTextUpTo20Min {
            get {
                return ResourceManager.GetString("ButtonTextUpTo20Min", resourceCulture);
            }
        }
        
        internal static string TitleTextHowLateWillYouBe {
            get {
                return ResourceManager.GetString("TitleTextHowLateWillYouBe", resourceCulture);
            }
        }
        
        internal static string ButtonTextWilBeLate {
            get {
                return ResourceManager.GetString("ButtonTextWilBeLate", resourceCulture);
            }
        }
        
        internal static string ParticipantWillBeLate {
            get {
                return ResourceManager.GetString("ParticipantWillBeLate", resourceCulture);
            }
        }
        
        internal static string TitleTextMessageSent {
            get {
                return ResourceManager.GetString("TitleTextMessageSent", resourceCulture);
            }
        }
        
        internal static string ButtonTextReplyInChat {
            get {
                return ResourceManager.GetString("ButtonTextReplyInChat", resourceCulture);
            }
        }
        
        internal static string TitleTextTypeOfMeeting {
            get {
                return ResourceManager.GetString("TitleTextTypeOfMeeting", resourceCulture);
            }
        }
        
        internal static string ButtonTextOnline {
            get {
                return ResourceManager.GetString("ButtonTextOnline", resourceCulture);
            }
        }
        
        internal static string ButtonTextOffline {
            get {
                return ResourceManager.GetString("ButtonTextOffline", resourceCulture);
            }
        }
        
        internal static string TitleTextOfflineMeeting {
            get {
                return ResourceManager.GetString("TitleTextOfflineMeeting", resourceCulture);
            }
        }
        
        internal static string TitleTextFinishRegistration {
            get {
                return ResourceManager.GetString("TitleTextFinishRegistration", resourceCulture);
            }
        }
    }
}
